services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialmedia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: SocialMedia
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/socialmedia_db?sslmode=disable
      JWT_SECRET: 1wpyKV0ZKYptRWoJwh7eQzjsC6XuqVolzet+nd4A1Y0=
    ports:
      - "8080:8080"

  post-service:
    build:
      context: SocialMedia
      dockerfile: post-service/Dockerfile
    container_name: post-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/socialmedia_db?sslmode=disable
      JWT_SECRET: 1wpyKV0ZKYptRWoJwh7eQzjsC6XuqVolzet+nd4A1Y0=
    ports:
      - "9090:8080"

  profile-service:
    build:
      context: SocialMedia
      dockerfile: profile-service/Dockerfile
    container_name: profile-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/socialmedia_db?sslmode=disable
      JWT_SECRET: 1wpyKV0ZKYptRWoJwh7eQzjsC6XuqVolzet+nd4A1Y0=
    ports:
      - "7070:8080"


volumes:
  postgres_data: